name: notify
on:
  push:
    branches:
      - notify
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Start Notify
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          payload: |
            {
              "attachments": [
                {
                  "color": "2871a7",
                  "author_name": "${{ github.triggering_actor }}",
                  "author_link": "https://github.com/${{ github.triggering_actor }}",
                  "author_icon": "https://github.com/${{ github.triggering_actor }}.png?size=40",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "thumb_url": "http://placekitten.com/g/200/200",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    },
                    {
                      "title": "Event",
                      "short": true,
                      "value": "${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Deploy Complete Notify
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "color": "28a745",
                  "author_name": "${{ github.triggering_actor }}",
                  "author_link": "https://github.com/${{ github.triggering_actor }}",
                  "author_icon": "https://github.com/${{ github.triggering_actor }}.png?size=40",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "thumb_url": "http://placekitten.com/g/200/200",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    },
                    {
                      "title": "Event",
                      "short": true,
                      "value": "${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - name: Deploy Failure Notify
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "color": "a7283e",
                  "author_name": "${{ github.triggering_actor }}",
                  "author_link": "https://github.com/${{ github.triggering_actor }}",
                  "author_icon": "https://github.com/${{ github.triggering_actor }}.png?size=40",
                  "title": "${{ github.repository }}",
                  "title_link": "https://github.com/${{ github.repository }}",
                  "thumb_url": "http://placekitten.com/g/200/200",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    },
                    {
                      "title": "Event",
                      "short": true,
                      "value": "${{ github.event_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
