name: notify
on:
  push:
    branches:
      - notify
jobs:
  call-in-progress-notify:
    use: ./.github/workflows/inProgressNotify.yml
  body:
    runs-on: ubuntu-latest
    needs: call-in-progress-notify
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
  call-complete-notify:
    use: ./.github/workflows/completeNotify.yml
    needs: body
    with:
      ts: ${{ jobs.call-in-progress-notify.outputs.ts }}
  call-failure-notify:
    use: ./.github/workflows/failureNotify.yml
    needs: body
    with:
      ts: ${{ jobs.call-in-progress-notify.outputs.ts }}
