name: notify
on:
  push:
    branches:
      - notify-legacy
jobs:
  call-in-progress-notify:
    uses: ./.github/workflows/inProgressNotify.yml
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
  body:
    runs-on: ubuntu-latest
    needs: call-in-progress-notify
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
  call-complete-notify:
    needs: [body, call-in-progress-notify]
    uses: ./.github/workflows/completeNotify.yml
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
      time: ${{ needs.call-in-progress-notify.outputs.time }}
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
  call-failure-notify:
    needs: [body, call-in-progress-notify]
    if: ${{ failure() }}
    uses: ./.github/workflows/failureNotify.yml
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
      time: ${{ needs.call-in-progress-notify.outputs.time }}
    secrets:
      slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
