name: notify
on:
  push:
    branches:
      - notify
jobs:
  call-in-progress-notify:
    uses: ./.github/workflows/inProgressNotify.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  body:
    runs-on: ubuntu-latest
    needs: call-in-progress-notify
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
  call-complete-notify:
    uses: ./.github/workflows/completeNotify.yml
    needs: [body, call-in-progress-notify]
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  call-failure-notify:
    uses: ./.github/workflows/failureNotify.yml
    needs: [body, call-in-progress-notify]
    with:
      ts: ${{ needs.call-in-progress-notify.outputs.ts }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
