name: notify
on:
  push:
    branches:
      - notify
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Start Notify
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Deploy Complete Notify
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - name: Deploy Failure Notify
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04T31UQSQ2'
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Failed)",
              "attachments": [
                {
                  "pretext": "Deployment failed",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
